package ipd12.java3.project.tankswar;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    Thread paintPanelThread;
    GamePanel paintPanel;
    Database db;
    File f;
    ArrayList<Tank> listTanks;
    ArrayList<Bullet> listBullets;

    public MainFrame() {

        try {
            this.db = new Database();
            initComponents();
            setIcon();
            menuFile.setMnemonic('G');
            menuExit.setMnemonic('E');
            f = new File("src\\res\\", "gamelog.csv");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Fatal error: unable to connect to database:\n" + ex.getMessage(),
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
            //dispose();//can't continue if database connection failed
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg = new javax.swing.JDialog();
        dlg_cbTankMoveSpeed = new javax.swing.JComboBox<>();
        dlg_cbEnemyMoveSpeed = new javax.swing.JComboBox<>();
        dlg_cbBulletSpeed = new javax.swing.JComboBox<>();
        dlg_lblTankMoveSpeed = new javax.swing.JLabel();
        dlg_lblEnemyNumber = new javax.swing.JLabel();
        dlg_lblBulletSpeed = new javax.swing.JLabel();
        dlg_tfEnemyNumber = new javax.swing.JTextField();
        dlg_rbtSinglePlayer = new javax.swing.JRadioButton();
        dlg_rbtDoublePlayer = new javax.swing.JRadioButton();
        dlg_lblPlayerOneName = new javax.swing.JLabel();
        dlg_lblPlayerTwoName = new javax.swing.JLabel();
        dlg_tfPlayer1Name = new javax.swing.JTextField();
        dlg_tfPlayer2Name = new javax.swing.JTextField();
        dlg_btCancel = new javax.swing.JButton();
        dlg_btSave = new javax.swing.JButton();
        dlg_rbtNormalMode = new javax.swing.JRadioButton();
        dlg_rbtOptionalMode = new javax.swing.JRadioButton();
        dlg_lblSelectLevel = new javax.swing.JLabel();
        dlg_gbtGameMode = new javax.swing.ButtonGroup();
        dlg_gbtSelectionMode = new javax.swing.ButtonGroup();
        pStart = new javax.swing.JPanel();
        btStartGame = new javax.swing.JButton();
        lblTankWar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuSettings = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();

        dlg.setTitle("Setting game");
        dlg.setLocationByPlatform(true);

        dlg_cbTankMoveSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        dlg_cbEnemyMoveSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        dlg_cbBulletSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        dlg_lblTankMoveSpeed.setText("Tank  move speed:");

        dlg_lblEnemyNumber.setText("Enemy number:");

        dlg_lblBulletSpeed.setText("Bullet speed:");

        dlg_gbtGameMode.add(dlg_rbtSinglePlayer);
        dlg_rbtSinglePlayer.setText("Single_Player");

        dlg_gbtGameMode.add(dlg_rbtDoublePlayer);
        dlg_rbtDoublePlayer.setText("Double_Player");

        dlg_lblPlayerOneName.setText("Palyer 1 name:");

        dlg_lblPlayerTwoName.setText("Player 2 name:");

        dlg_btCancel.setText("Cancel");

        dlg_btSave.setText("Save");

        dlg_gbtSelectionMode.add(dlg_rbtNormalMode);
        dlg_rbtNormalMode.setText("Normal Mode");

        dlg_gbtSelectionMode.add(dlg_rbtOptionalMode);
        dlg_rbtOptionalMode.setText("Optional Mode");

        dlg_lblSelectLevel.setText("Select level:");

        javax.swing.GroupLayout dlgLayout = new javax.swing.GroupLayout(dlg.getContentPane());
        dlg.getContentPane().setLayout(dlgLayout);
        dlgLayout.setHorizontalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dlgLayout.createSequentialGroup()
                            .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dlgLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(dlg_lblTankMoveSpeed)
                                    .addGap(18, 18, 18)
                                    .addComponent(dlg_cbEnemyMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(dlg_lblBulletSpeed)
                                        .addGap(18, 18, 18)
                                        .addComponent(dlg_cbBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgLayout.createSequentialGroup()
                                        .addComponent(dlg_lblEnemyNumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dlg_tfEnemyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgLayout.createSequentialGroup()
                                        .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dlg_lblPlayerOneName)
                                            .addComponent(dlg_lblPlayerTwoName))
                                        .addGap(18, 18, 18)
                                        .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dlg_tfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dlg_tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addContainerGap(31, Short.MAX_VALUE))
                        .addGroup(dlgLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlg_btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dlg_btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dlgLayout.createSequentialGroup()
                        .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgLayout.createSequentialGroup()
                                .addComponent(dlg_rbtSinglePlayer)
                                .addGap(18, 18, 18)
                                .addComponent(dlg_rbtDoublePlayer))
                            .addGroup(dlgLayout.createSequentialGroup()
                                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dlg_rbtNormalMode)
                                    .addComponent(dlg_lblSelectLevel))
                                .addGap(18, 18, 18)
                                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlg_rbtOptionalMode)
                                    .addComponent(dlg_cbTankMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        dlgLayout.setVerticalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_rbtSinglePlayer)
                    .addComponent(dlg_rbtDoublePlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_rbtNormalMode)
                    .addComponent(dlg_rbtOptionalMode))
                .addGap(21, 21, 21)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblSelectLevel)
                    .addComponent(dlg_cbTankMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_cbEnemyMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlg_lblTankMoveSpeed))
                .addGap(30, 30, 30)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_cbBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlg_lblBulletSpeed))
                .addGap(25, 25, 25)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblEnemyNumber)
                    .addComponent(dlg_tfEnemyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblPlayerOneName)
                    .addComponent(dlg_tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblPlayerTwoName)
                    .addComponent(dlg_tfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_btCancel)
                    .addComponent(dlg_btSave))
                .addGap(44, 44, 44))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank War");
        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        pStart.setBackground(java.awt.Color.white);

        btStartGame.setText("Start Game");
        btStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartGameActionPerformed(evt);
            }
        });

        lblTankWar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTankWar.setText("Tank War");

        jLabel1.setText("Design by Ipd12 ");

        javax.swing.GroupLayout pStartLayout = new javax.swing.GroupLayout(pStart);
        pStart.setLayout(pStartLayout);
        pStartLayout.setHorizontalGroup(
            pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(pStartLayout.createSequentialGroup()
                .addGroup(pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pStartLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btStartGame))
                    .addGroup(pStartLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblTankWar)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        pStartLayout.setVerticalGroup(
            pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStartLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lblTankWar)
                .addGap(107, 107, 107)
                .addComponent(btStartGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(pStart, java.awt.BorderLayout.CENTER);

        menuFile.setText("Game");

        menuSave.setText("Save&Exit");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuSave);
        menuFile.add(jSeparator1);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        jMenu1.setText("Setting");

        menuSettings.setText("Settings");
        menuSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(menuSettings);
        jMenu1.add(jSeparator4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartGameActionPerformed
        // Goes to main page and start game
        try {
            paintPanel = new GamePanel();
            f.fileReader();
        } catch (java.lang.IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "The file can't find !" + e.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file read faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
        paintPanelThread = new Thread(paintPanel);
        paintPanelThread.start();
        setFocusable(true);
        paintPanel.setBackground(java.awt.Color.white);
        this.remove(pStart);
        this.add(paintPanel);
        this.addKeyListener(paintPanel);
        this.setVisible(true);
    }//GEN-LAST:event_btStartGameActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed

    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        Object[] options = {"Exit", "Cancel"};
        int decision = JOptionPane.showOptionDialog(this,
                "Are you sure you want to Exit?\n",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null, //do not use a custom Icon
                options, //the titles of buttons
                options[1]); //default button title
        if (decision == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        try {
            f.fileWriter();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file write faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            f.fileWriter();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file write faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void menuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSettingsActionPerformed
        dlg.pack();
        dlg.setVisible(true);
    }//GEN-LAST:event_menuSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStartGame;
    private javax.swing.JDialog dlg;
    private javax.swing.JButton dlg_btCancel;
    private javax.swing.JButton dlg_btSave;
    private javax.swing.JComboBox<String> dlg_cbBulletSpeed;
    private javax.swing.JComboBox<String> dlg_cbEnemyMoveSpeed;
    private javax.swing.JComboBox<String> dlg_cbTankMoveSpeed;
    private javax.swing.ButtonGroup dlg_gbtGameMode;
    private javax.swing.ButtonGroup dlg_gbtSelectionMode;
    private javax.swing.JLabel dlg_lblBulletSpeed;
    private javax.swing.JLabel dlg_lblEnemyNumber;
    private javax.swing.JLabel dlg_lblPlayerOneName;
    private javax.swing.JLabel dlg_lblPlayerTwoName;
    private javax.swing.JLabel dlg_lblSelectLevel;
    private javax.swing.JLabel dlg_lblTankMoveSpeed;
    private javax.swing.JRadioButton dlg_rbtDoublePlayer;
    private javax.swing.JRadioButton dlg_rbtNormalMode;
    private javax.swing.JRadioButton dlg_rbtOptionalMode;
    private javax.swing.JRadioButton dlg_rbtSinglePlayer;
    private javax.swing.JTextField dlg_tfEnemyNumber;
    private javax.swing.JTextField dlg_tfPlayer1Name;
    private javax.swing.JTextField dlg_tfPlayer2Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblTankWar;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSettings;
    private javax.swing.JPanel pStart;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        try {
            setIconImage(ImageIO.read(getClass().getResourceAsStream("/res//iconFrame.png")));
        } catch (java.lang.NullPointerException | IOException e) {
            JOptionPane.showMessageDialog(this,
                    "The Icon can't find !" + e.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }
}
