package ipd12.java3.project.tankswar;

import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    Thread paintPanelThread;
    GamePanel gamePanel;
    Database db;
    File f;
    File fHighestRecord;

    public MainFrame() {

        try {
            this.db = new Database();
            initComponents();
            setIcon();
            menuGame.setMnemonic('G');
            menuExit.setMnemonic('E');
            menubarSetting.setMnemonic('S');
            menuSettings.setMnemonic('S');
            f = new File("src\\res\\", "gamelog.csv");
            fHighestRecord = new File("src\\res\\", "highestRecord.csv");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Fatal error: unable to connect to database:\n" + ex.getMessage(),
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
            //dispose();//can't continue if database connection failed
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg = new javax.swing.JDialog();
        dlg_cbPlayerMoveSpeed = new javax.swing.JComboBox<>();
        dlg_cbPlayerBulletSpeed = new javax.swing.JComboBox<>();
        dlg_lblTankMoveSpeed = new javax.swing.JLabel();
        dlg_lblEnemyNumber = new javax.swing.JLabel();
        dlg_lblBulletSpeed = new javax.swing.JLabel();
        dlg_lblPlayerOneName = new javax.swing.JLabel();
        dlg_lblPlayerTwoName = new javax.swing.JLabel();
        dlg_tfPlayer1Name = new javax.swing.JTextField();
        dlg_tfPlayer2Name = new javax.swing.JTextField();
        dlg_btCancel = new javax.swing.JButton();
        dlg_btSave = new javax.swing.JButton();
        dlg_cbEnemyNumber = new javax.swing.JComboBox<>();
        dlg_gbtSelectionMode = new javax.swing.ButtonGroup();
        pStart = new javax.swing.JPanel();
        btStartGame = new javax.swing.JButton();
        lblTankWar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGame = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuReplay = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menubarSetting = new javax.swing.JMenu();
        menuSettings = new javax.swing.JMenuItem();

        dlg.setTitle("Setting game");
        dlg.setLocationByPlatform(true);

        dlg_cbPlayerMoveSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        dlg_cbPlayerBulletSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        dlg_lblTankMoveSpeed.setText("Tank  move speed:");

        dlg_lblEnemyNumber.setText("Enemy number:");

        dlg_lblBulletSpeed.setText("Bullet speed:");

        dlg_lblPlayerOneName.setText("Palyer 1 name:");

        dlg_lblPlayerTwoName.setText("Player 2 name:");

        dlg_btCancel.setText("Cancel");
        dlg_btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlg_btCancelActionPerformed(evt);
            }
        });

        dlg_btSave.setText("Save");
        dlg_btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlg_btSaveActionPerformed(evt);
            }
        });

        dlg_cbEnemyNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        javax.swing.GroupLayout dlgLayout = new javax.swing.GroupLayout(dlg.getContentPane());
        dlg.getContentPane().setLayout(dlgLayout);
        dlgLayout.setHorizontalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(dlg_btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dlg_btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dlgLayout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(dlg_lblTankMoveSpeed)
                            .addGap(18, 18, 18)
                            .addComponent(dlg_cbPlayerMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dlgLayout.createSequentialGroup()
                            .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlg_lblPlayerOneName)
                                .addComponent(dlg_lblPlayerTwoName))
                            .addGap(18, 18, 18)
                            .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlg_tfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dlg_tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(dlgLayout.createSequentialGroup()
                            .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dlgLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(dlg_lblBulletSpeed))
                                .addComponent(dlg_lblEnemyNumber))
                            .addGap(18, 18, 18)
                            .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlg_cbEnemyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dlg_cbPlayerBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        dlgLayout.setVerticalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_cbPlayerMoveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlg_lblTankMoveSpeed))
                .addGap(30, 30, 30)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_cbPlayerBulletSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlg_lblBulletSpeed))
                .addGap(25, 25, 25)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblEnemyNumber)
                    .addComponent(dlg_cbEnemyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblPlayerOneName)
                    .addComponent(dlg_tfPlayer1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_lblPlayerTwoName)
                    .addComponent(dlg_tfPlayer2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlg_btCancel)
                    .addComponent(dlg_btSave))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank War");
        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        pStart.setBackground(java.awt.Color.white);

        btStartGame.setText("Start Game");
        btStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartGameActionPerformed(evt);
            }
        });

        lblTankWar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTankWar.setText("Tank War");

        jLabel1.setText("Design by Ipd12 ");

        javax.swing.GroupLayout pStartLayout = new javax.swing.GroupLayout(pStart);
        pStart.setLayout(pStartLayout);
        pStartLayout.setHorizontalGroup(
            pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(pStartLayout.createSequentialGroup()
                .addGroup(pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pStartLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btStartGame))
                    .addGroup(pStartLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblTankWar)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        pStartLayout.setVerticalGroup(
            pStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStartLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lblTankWar)
                .addGap(107, 107, 107)
                .addComponent(btStartGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(pStart, java.awt.BorderLayout.CENTER);

        menuGame.setText("Game");

        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuGame.add(menuSave);
        menuGame.add(jSeparator1);

        menuReplay.setText("Replay");
        menuReplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReplayActionPerformed(evt);
            }
        });
        menuGame.add(menuReplay);
        menuGame.add(jSeparator2);

        menuExit.setText("Exit(Alt+E)");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuGame.add(menuExit);

        jMenuBar1.add(menuGame);

        menubarSetting.setText("Setting");

        menuSettings.setText("Settings(Alt+S)");
        menuSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSettingsActionPerformed(evt);
            }
        });
        menubarSetting.add(menuSettings);

        jMenuBar1.add(menubarSetting);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartGameActionPerformed
        // Goes to main page and start game
        try {
            //Retrieve the record from file
            f.fileReader();
            fHighestRecord.fileReaderHighestRecord();
            gamePanel = new GamePanel();
        } catch (java.lang.IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "The file can't find !" + e.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file write faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);

        }
        paintPanelThread = new Thread(gamePanel);
        paintPanelThread.start();
        setFocusable(true);
        gamePanel.setBackground(java.awt.Color.white);
        this.remove(pStart);
        this.add(gamePanel);
        this.addKeyListener(gamePanel);
        this.setVisible(true);
    }//GEN-LAST:event_btStartGameActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        try {
            if (GamePanel.tanks.get(0).isIsAlive()) {
                db.addTank(GamePanel.tanks.get(0));
            }
            if (GamePanel.tanks.get(1).isIsAlive()) {
                db.addTank(GamePanel.tanks.get(1));
            }
            for (int i = 2; i < GamePanel.tanks.size(); i++) {
                if (GamePanel.tanks.get(i).isIsAlive()) {
                    db.addTank(GamePanel.tanks.get(i));
                }
            }
            for (int i = 0; i < GamePanel.bullets.size(); i++) {
                if (GamePanel.bullets.get(i).isIsAlive()) {
                    db.addBullet(GamePanel.bullets.get(i));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error adding record: " + e.getMessage(),
                    "Database error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        Object[] options = {"Exit", "Cancel"};
        int decision = JOptionPane.showOptionDialog(this,
                "Are you sure you want to Exit?\n",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null, //do not use a custom Icon
                options, //the titles of buttons
                options[1]); //default button title
        if (decision == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        writerHighestRecord();
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        writerHighestRecord();
    }//GEN-LAST:event_formWindowClosing

    private void writerHighestRecord() {
        try {
            if (Record.heightRecord < Record.currentRecord) {
                Record.heightRecord = Record.currentRecord;
                fHighestRecord.fileWriterHighestRecord();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file write faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void menuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSettingsActionPerformed
        dlg.pack();
        dlg.setVisible(true);
    }//GEN-LAST:event_menuSettingsActionPerformed

    private void menuReplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReplayActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Replay last game in future ",
                "Future plan",
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuReplayActionPerformed

    private void dlg_btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlg_btCancelActionPerformed
        dlg.setVisible(false);
    }//GEN-LAST:event_dlg_btCancelActionPerformed

    private void dlg_btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlg_btSaveActionPerformed
        try {
            int playerMoveSpeed = Integer.parseInt(dlg_cbPlayerMoveSpeed.getSelectedItem().toString());
            int playerBulletSpeed = Integer.parseInt(dlg_cbPlayerBulletSpeed.getSelectedItem().toString());
            int enemyNumber = Integer.parseInt(dlg_cbEnemyNumber.getSelectedItem().toString());
            String playerOneName = dlg_tfPlayer1Name.getText();
            String playerTwoName = dlg_tfPlayer2Name.getText();
            if (playerOneName.length() < 1 || playerOneName.length() > 20) {
                throw new IllegalArgumentException("player 1 Name must be between 1 and 20 character.");
            }
            if (playerTwoName.length() < 1 || playerTwoName.length() > 20) {
                throw new IllegalArgumentException("player 2 Name must be between 1 and 20 character.");
            }
            f.fileWriter(playerMoveSpeed, playerBulletSpeed, enemyNumber, playerOneName, playerTwoName);
            Object[] options = {"Restart", "Cancel"};
            int decision = JOptionPane.showOptionDialog(this,
                    "Are you sure you want to save Settings and Exit?\n",
                    "Confirm Exit",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null, //do not use a custom Icon
                    options, //the titles of buttons
                    options[1]); //default button title
            if (decision == JOptionPane.YES_OPTION) {
                System.exit(0);
                dlg.setVisible(false);
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "Format error: can't : " + e.getMessage(),
                    "Input error",
                    JOptionPane.WARNING_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "The file write faild !" + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dlg_btSaveActionPerformed

    private void setIcon() {
        try {
            setIconImage(ImageIO.read(getClass().getResourceAsStream("/res//iconFrame.png")));
        } catch (java.lang.NullPointerException | IOException e) {
            JOptionPane.showMessageDialog(this,
                    "The Icon can't find !" + e.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStartGame;
    private javax.swing.JDialog dlg;
    private javax.swing.JButton dlg_btCancel;
    private javax.swing.JButton dlg_btSave;
    private javax.swing.JComboBox<String> dlg_cbEnemyNumber;
    private javax.swing.JComboBox<String> dlg_cbPlayerBulletSpeed;
    private javax.swing.JComboBox<String> dlg_cbPlayerMoveSpeed;
    private javax.swing.ButtonGroup dlg_gbtSelectionMode;
    private javax.swing.JLabel dlg_lblBulletSpeed;
    private javax.swing.JLabel dlg_lblEnemyNumber;
    private javax.swing.JLabel dlg_lblPlayerOneName;
    private javax.swing.JLabel dlg_lblPlayerTwoName;
    private javax.swing.JLabel dlg_lblTankMoveSpeed;
    private javax.swing.JTextField dlg_tfPlayer1Name;
    private javax.swing.JTextField dlg_tfPlayer2Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblTankWar;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuGame;
    private javax.swing.JMenuItem menuReplay;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSettings;
    private javax.swing.JMenu menubarSetting;
    private javax.swing.JPanel pStart;
    // End of variables declaration//GEN-END:variables
}
