/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipd12.java3.project.tankswar;

/**
 *
 * @author Aneeta
 */
public class TanksWar extends javax.swing.JFrame {

    /**
     * Creates new form TanksWar
     */
    public TanksWar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new java.awt.Panel();
        btLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        panelStart = new java.awt.Panel();
        pStart_lblMessage = new javax.swing.JLabel();
        panelStart_btStartGame = new javax.swing.JButton();
        panelSettings_btSettings = new javax.swing.JButton();
        panelPlay = new java.awt.Panel();
        panelSettings = new java.awt.Panel();
        panelSettings_lblColor = new javax.swing.JLabel();
        panelSettings_lblModel = new javax.swing.JLabel();
        panelSettings_lblTotalEnemy = new javax.swing.JLabel();
        panelSettings_tfTankColor = new javax.swing.JTextField();
        panelSettings_cbTankModel = new javax.swing.JComboBox<>();
        panelSettings_sEnemyNumber = new javax.swing.JSlider();
        panelSettings_lblEnemyNumberValue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 100, 40));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setText("Username:");
        panelLogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 30));
        panelLogin.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, -1));

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelLogin.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 420, 70));

        getContentPane().add(panelLogin, "card3");

        panelStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pStart_lblMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pStart_lblMessage.setText("Welcome to Tanks War, Guest!");
        panelStart.add(pStart_lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 270, 40));
        pStart_lblMessage.getAccessibleContext().setAccessibleName("");

        panelStart_btStartGame.setText("Play!");
        panelStart.add(panelStart_btStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 143, 100, 50));

        panelSettings_btSettings.setText("Settings");
        panelStart.add(panelSettings_btSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 100, 50));

        getContentPane().add(panelStart, "card3");

        panelPlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelPlay, "card4");

        panelSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSettings_lblColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelSettings_lblColor.setText("Tank color:");
        panelSettings.add(panelSettings_lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, 30));

        panelSettings_lblModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelSettings_lblModel.setText("Tank model:");
        panelSettings_lblModel.setToolTipText("");
        panelSettings.add(panelSettings_lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, 30));

        panelSettings_lblTotalEnemy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelSettings_lblTotalEnemy.setText("Enemy number:");
        panelSettings.add(panelSettings_lblTotalEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        panelSettings.add(panelSettings_tfTankColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, -1));

        panelSettings_cbTankModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model 1", "Model 2", "Model 3", "Model 4", "Model 5" }));
        panelSettings.add(panelSettings_cbTankModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        panelSettings_sEnemyNumber.setMajorTickSpacing(5);
        panelSettings_sEnemyNumber.setMaximum(20);
        panelSettings_sEnemyNumber.setMinimum(1);
        panelSettings_sEnemyNumber.setMinorTickSpacing(1);
        panelSettings_sEnemyNumber.setPaintLabels(true);
        panelSettings_sEnemyNumber.setPaintTicks(true);
        panelSettings_sEnemyNumber.setSnapToTicks(true);
        panelSettings_sEnemyNumber.setToolTipText("");
        panelSettings_sEnemyNumber.setValue(10);
        panelSettings.add(panelSettings_sEnemyNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 270, -1));

        panelSettings_lblEnemyNumberValue.setText("2");
        panelSettings.add(panelSettings_lblEnemyNumberValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, 20));

        getContentPane().add(panelSettings, "card5");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        /*String message = "Welcome to Tanks War, " + tfUsername.getText();
        lblMessage.setText(message);
         */
        panelLogin.setVisible(false);
        panelStart.setVisible(true);
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TanksWar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TanksWar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TanksWar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TanksWar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TanksWar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel pStart_lblMessage;
    private java.awt.Panel panelLogin;
    private java.awt.Panel panelPlay;
    private java.awt.Panel panelSettings;
    private javax.swing.JButton panelSettings_btSettings;
    private javax.swing.JComboBox<String> panelSettings_cbTankModel;
    private javax.swing.JLabel panelSettings_lblColor;
    private javax.swing.JLabel panelSettings_lblEnemyNumberValue;
    private javax.swing.JLabel panelSettings_lblModel;
    private javax.swing.JLabel panelSettings_lblTotalEnemy;
    private javax.swing.JSlider panelSettings_sEnemyNumber;
    private javax.swing.JTextField panelSettings_tfTankColor;
    private java.awt.Panel panelStart;
    private javax.swing.JButton panelStart_btStartGame;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
